# Generated by Django 5.0.4 on 2024-05-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Promotion',
        ),
        migrations.RemoveField(
            model_name='promo',
            name='Niveau',
        ),
        migrations.AddField(
            model_name='module',
            name='Niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='niveau',
            name='Promotion',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='promo.promo'),
            preserve_default=False,
        ),
    ]
