# Generated by Django 4.1.3 on 2024-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_remove_module_promotion_remove_promo_niveau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='spécialité',
            field=models.CharField(default='SIW', max_length=20),
            preserve_default=False,
        ),
    ]
