# Generated by Django 4.1.3 on 2024-05-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_app', '0002_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csv_app.person')),
            ],
            bases=('csv_app.person',),
        ),
    ]
